### ISSUE TITLE
Apply Caido filters to requests being processed

### ISSUE THREAD

**Issue by Splinter0** [caido-community/authmatrix#12]
First of all thanks a lot for this plugin, I was in the process of building one myself and then stumbled upon this one.

It is currently quite tedious to manually remove all the static files requests intercepted, like images and scripts, especially because they are explicitly excluded from other tools via the filters. It would be nice if there was a filter presets selector (or default to the ones activated for http history).

Let me know if you'll accept PR, I'll be happy to implement this as soon as I have time :)

**Comment by Corb3nik** [comment]
Hey @Splinter0!

PRs are welcome :) The Authmatrix is pretty beta right now so any improvements are welcome.

Filtering would be great. I'm thinking we could have a similar bar as: ![Image](https://github.com/user-attachments/assets/250c7fca-1422-43fa-bb93-d501695651ff)

... but at the top of the Authmatrix page.

Main problem though is that we don't have the backend plugin APIs to check if a request matches a given HTTPQL query yet. So this feature might be tough to do right now. 

I created an issue for it and we'll discuss about it on Friday :) https://github.com/caido/caido/issues/1233

**Comment by Splinter0** [comment]
Beautiful! HTTPQL bar would be perfect.

P.S. I'm using the plugin quite a lot and I have some improvements in mind, I will shoot some PRs over hopefully this weekend, would you like me to create some issues so you can decide whether it's an improvement you are interested in or not?

**Comment by Corb3nik** [comment]
@Splinter0 Yes please, it'll also allow other people to work on these issues too :)

**Comment by Splinter0** [comment]
It seems that it is already possible to use: https://developer.caido.io/reference/sdks/backend/#filter to provide an HTTPQL filter for requests, should we go ahead and implement a solution with that or do you want to wait for the caido native solution to be available?

**Comment by Splinter0** [comment]
Additionally, this is originally what I meant with applying the filters, the ones set up in this tab, but I think adding the HTTPQL bar is also a good idea.

![Screenshot from 2024-10-21 01-53-58](https://github.com/user-attachments/assets/87c46cf8-7815-4218-8a25-9b0d2909b989)

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido-community/authmatrix/pull/25
