### ISSUE TITLE
Add option to run Analyze in the background

### ISSUE THREAD

**Issue by Splinter0** [caido-community/authmatrix#13]
It would be very nice if the plugin would run Analyze in the background while the tester can keep browsing with the "high privilege" account.

Willing to implement this if accepting PRs.

**Comment by Corb3nik** [comment]
@Splinter0 Yep! Would love that. I was thinking of an "Auto-analyze" checkbox that we can add close to the "Analyze" button.

Authmatrix works by specifying which roles/users should have access to a resource.

What should the default behavior be? I guess all roles/users would be unchecked?

**Comment by Splinter0** [comment]
I think so, all would be unchecked and then based on what you check the status changes, perhaps it might be nice then to integrate with the findings tab so that it does not get confusing. What do you think?

**Comment by Corb3nik** [comment]
Could be interesting. I would start with just the auto-analysis first, and add something for the findings later down the road if we find it confusing.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido-community/authmatrix/pull/15
