### ISSUE TITLE
Group same request under the same row

### ISSUE THREAD

**Issue by Splinter0** [caido-community/authmatrix#14]
Right now it is quite noisy as requests that are repeated do not get grouped and instead are treated as completely new requests. This messes up the table a bit and also make the analyze process slower.

**Comment by Corb3nik** [comment]
Good idea :) Challenge here is to figure out how identify duplicate requests... Is creating a signature from `VERB + HOST + PATH + QUERY PARAMS` enough? Or do we want to take the HTTP bodies into account?

**Comment by Splinter0** [comment]
I think we could start by grouping the GET requests, then in the future figure out some sort of way of grouping requests under the same path maybe with some sort of dropdown solution or similar, what do you think?

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido-community/authmatrix/pull/20
