### ISSUE TITLE
Add request path to dashboard column

### ISSUE THREAD

**Issue by Splinter0** [caido-community/authmatrix#16]
Usually when working with authmatrix I'm testing only a few domains at the time, which means that showing the domain only in the table is quite uninformative. It would be nice to have the actual request path in the table. 

Some options/ideas:
- Add another column
- Simply append to the existing URL column
- Only show path unless a secondary domain is detected

Also the port is not very useful when it's the default `443` or `80` because anyway that is expressed by the protocol of the url.

**Comment by Corb3nik** [comment]
I think have a second column is only relevant if we plan on sorting them. I'd always append to the existing URL column.

Also yeah, removing the 443/80 when not needed would be great 👍

**Comment by Corb3nik** [comment]
Closed via #19
