### ISSUE TITLE
Update bypassed status when checking role/user checkbox

### ISSUE THREAD

**Issue by Splinter0** [caido-community/authmatrix#17]
Currently the bypassed status does not update by checking the box. 

Example: request gets replayed with lower access, however it's supposed to be available for the access level expressed in the tickbox, the status should change to "enforced" without having to run analyze again

**Comment by Corb3nik** [comment]
Agreed!

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido-community/authmatrix/pull/20
